name: "build-test"
on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v3

      - uses: ./
        with:
          xcresult-path: __tests__/data/TestResult.xcresult
          output-md: test-summary.md

      - uses: ./
        with:
          xcresult-path: __tests__/data/TestResult.xcresult
          show-test-results: all
          output-md: test-summary-all-tests.md

      - uses: ./
        with:
          xcresult-path: __tests__/data/TestResult.xcresult
          show-test-results: failed
          output-md: test-summary-failed-tests.md

      - name: check test-summary.md
        run: |
          if [ ! -f test-summary.md ]; then
            echo "❌ test-summary.md was not generated."
            exit 1
          else
            echo "✅ test-summary.md was generated successfully."
          fi
